apiVersion: v1
kind: Service
metadata:
  name: python
spec:
  type: NodePort
  ports:
  - targetPort: 3000
    port: 3000
    nodePort: 32000
  selector:
    app: python-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  selector:
    matchLabels:
      app: python-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - image: 127.0.0.1:5000/local/python-app
        name: python-app
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: python-app
        env:
        - name: MYSQL_USERNAME
          value: root
        - name: MYSQL_PASSWORD
          value: password
        - name: MYSQL_INSTANCE_NAME
          value: mysql
        - name: MYSQL_PORT_3306_TCP_ADDR
          value: mysql
        - name: MYSQL_PORT_3306_TCP_PORT
          value: '3306'

